[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"


[project]
name = "ryan-ppo"
version = "1.0.0"
description = "PPO implementation for NVIDIA Isaac Lab, with sim2real transfer to the SO-ARM101 robot"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name="Ryan Donald" }
]
requires-python = ">=3.12"
dependencies = [
  "torch >= 2.7.0",
  "numpy >= 1.26.4",
  "rich",
  "wandb",
  "gymnasium",
]

[dependency-groups]
dev = [
  "pytest",
  "ruff",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.isort]
known-first-party = ["ryan_ppo", "ryan_tasks"]
known-third-party = ["wandb", "gymnasium", "isaaclab_tasks", "torch", "numpy"]
